cors.originPatterns: http://localhost:8080,http://localhost:3000,http://localhost:5173
spring.application.name=flightradar


#spring.profiles.active=test

spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/flight_radar_api?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false