# Configuracoes de CORS
cors.originPatterns: http://localhost:8080,http://localhost:3000,http://localhost:5173

# Porta do servidor
server.port=8090

# Configuracao do temporizador
simulation.scheduler.fixed-rate-ms=2000
simulation.scheduler.start-pending-flights-rate-ms=5000
simulation.scheduler.update-database-rate-ms=300000

# Nome da aplicacao
spring.application.name=flightradar

# Configuracoes do MySQL
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}?useSSL=false&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Configuracoes da JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
