-- Inserindo 10 planos de voo com dados realistas, status variados e IDs fixos corretos.

INSERT INTO tb_flight_plan (
    id, flight_date, flight_phase,
    departure_timezone, departure_iata, departure_terminal, departure_gate,
    departure_scheduled, departure_estimated, departure_actual,
    arrival_timezone, arrival_iata, arrival_terminal, arrival_gate, arrival_baggage,
    arrival_scheduled, arrival_estimated, arrival_actual,
    flight_number, flight_iata, flight_icao, flight_codeshared, flight_cruise_altitude,
    live_updated, live_latitude, live_longitude, live_altitude, live_direction,
    live_speed_horizontal, live_speed_vertical, live_progress, live_is_ground,
    airline_id, aircraft_id, departure_airport_id, arrival_airport_id, route_id
)
VALUES
-- 1: Gol CGH -> SDU - AGENDADO (decola daqui a 2 min)
(1, CURDATE(), '0', 'America/Sao_Paulo', 'CGH', '1', '12A',
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 2 MINUTE),
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 2 MINUTE),
    NULL,
    'America/Sao_Paulo', 'SDU', '1', '22', '3',
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 1 HOUR),
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 1 HOUR),
    NULL,
    '2021', 'G32021', 'GLO2021', FALSE, 25000,
    NULL, -23.6261, -46.6558, 0, 0, 0, 0, 0, TRUE,
    10, 2, 41, 44, 1),

-- 2: Azul GRU -> REC - ATIVO (decolou há 1h)
(2, CURDATE(), '4', 'America/Sao_Paulo', 'GRU', '2', '208',
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 1 HOUR),
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 58 MINUTE),
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 1 HOUR),
    'America/Recife', 'REC', '1', 'B12', '5',
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 2 HOUR),
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 2 HOUR),
    NULL,
    '4010', 'AD4010', 'AZU4010', FALSE, 37000,
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 30 MINUTE),
    -15.6642, -39.6273, 37000.0, 45, 880, 0, 55, FALSE,
    11, 1, 40, 55, 2),

-- 3: LATAM GRU -> MIA - AGENDADO (decola daqui a 2 min)
(3, CURDATE(), '0', 'America/Sao_Paulo', 'GRU', '3', '315',
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 2 MINUTE),
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 2 MINUTE),
    NULL,
    'America/New_York', 'MIA', 'S', 'J17', '8',
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 8 HOUR),
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 8 HOUR),
    NULL,
    '8190', 'LA8190', 'LAN8190', FALSE, 38000,
    NULL, -23.4356, -46.4731, 0, 0, 0, 0, 0, TRUE,
    9, 5, 40, 9, 6),

-- 4: TAP GIG -> LIS - ATIVO (em rota há 3h)
(4, CURDATE(), '4', 'America/Sao_Paulo', 'GIG', '2', 'B44',
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 3 HOUR),
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 3 HOUR),
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 2 HOUR),
    'Europe/Lisbon', 'LIS', '1', '42', '8',
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 6 HOUR),
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 6 HOUR),
    NULL,
    '172', 'TP172', 'TAP172', FALSE, 39000,
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 30 MINUTE),
    0.0, -30.0, 39000.0, 35, 910, 0, 40, FALSE,
    23, 10, 43, 25, 7),

-- 5: Delta LAX -> JFK - POUSADO
(5, CURDATE(), '8', 'America/Los_Angeles', 'LAX', '2', '25A',
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 9 HOUR),
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 8 HOUR),
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 8 HOUR),
    'America/New_York', 'JFK', '4', 'B25', '5',
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 20 MINUTE),
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 20 MINUTE),
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 20 MINUTE),
    '417', 'DL417', 'DAL417', FALSE, 36000,
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 20 MINUTE),
    40.6397, -73.7789, 0, 0, 0, 0, 100, TRUE,
    2, 5, 5, 6, 10),

-- 6: Lufthansa LHR -> FRA - ATIVO
(6, CURDATE(), '4', 'Europe/London', 'LHR', '2', 'B32',
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 45 MINUTE),
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 44 MINUTE),
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 45 MINUTE),
    'Europe/Berlin', 'FRA', '1', 'A40', '3',
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 45 MINUTE),
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 45 MINUTE),
    NULL,
    '903', 'LH903', 'DLH903', FALSE, 28000,
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 10 MINUTE),
    50.5, 4.5, 28000.0, 95, 850, 0, 75, FALSE,
    15, 9, 14, 17, 18),

-- 7: Air France GRU -> CDG - AGENDADO
(7, CURDATE(), '0', 'America/Sao_Paulo', 'GRU', '3', '301',
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 2 MINUTE),
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 2 MINUTE),
    NULL,
    'Europe/Paris', 'CDG', '2E', 'M50', '22',
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 11 HOUR),
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 11 HOUR),
    NULL,
    '457', 'AF457', 'AFR457', FALSE, 39000,
    NULL, -23.4356, -46.4731, 0, 0, 0, 0, 0, TRUE,
    16, 8, 40, 15, 8),

-- 8: Emirates GIG -> DXB - AGENDADO
(8, CURDATE(), '0', 'America/Sao_Paulo', 'GIG', '2', 'C55',
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 2 MINUTE),
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 2 MINUTE),
    NULL,
    'Asia/Dubai', 'DXB', '3', 'F18', '11',
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 10 HOUR),
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 10 HOUR),
    NULL,
    '248', 'EK248', 'UAE248', FALSE, 41000,
    NULL, -22.8089, -43.2436, 0, 0, 0, 0, 0, TRUE,
    39, 11, 43, 26, 9),

-- 9: Singapore SIN -> LHR - POUSADO
(9, CURDATE(), '8', 'Asia/Singapore', 'SIN', '2', 'B5',
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 15 HOUR),
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 14 HOUR),
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 14 HOUR),
    'Europe/London', 'LHR', '2', 'C58', '19',
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 8 HOUR),
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 8 HOUR),
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 8 HOUR),
    '321', 'SQ321', 'SIA321', FALSE, 40000,
    DATE_SUB(UTC_TIMESTAMP(), INTERVAL 8 HOUR),
    51.4706, -0.4619, 0, 0, 0, 0, 100, TRUE,
    28, 13, 32, 14, 12),

-- 10: LATAM BSB -> MAO - AGENDADO
(10, CURDATE(), '0', 'America/Sao_Paulo', 'BSB', '1', '22',
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 2 MINUTE),
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 2 MINUTE),
    NULL,
    'America/Manaus', 'MAO', '1', '3', '4',
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 2 HOUR),
    DATE_ADD(UTC_TIMESTAMP(), INTERVAL 2 HOUR),
    NULL,
    '3578', 'LA3578', 'LAN3578', FALSE, 35000,
    NULL, -15.8692, -47.9172, 0, 0, 0, 0, 0, TRUE,
    9, 3, 50, 64, 31);
